# Generated by Django 4.0.5 on 2022-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='last_updated_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
